name: Build & Push Multi-Arch Distroless Image

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: "0 22 * * *"  # roda todo dia à 00:00 UTC

jobs:
  build-base-images:
    uses: ./.github/workflows/build-base-images.yml
    with:
      registry: gersontpc
      frameworks: '["java21", "java25", "python3-13", "python3-14", "go1-25", "go1-26", "nodejs22", "nodejs24", "dotnet8", "dotnet10"]'
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}